# Generated by Django 5.1.4 on 2025-01-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "ordering": ["name", "first_sending", "last_sending"],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.RemoveField(
            model_name="newsletter",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="newsletter",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="newsletter",
            name="first_sending",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время создания первой рассылки"),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="last_sending",
            field=models.DateField(blank=True, null=True, verbose_name="Дата и время последней рассылки"),
        ),
        migrations.AlterField(
            model_name="mailingrecipient",
            name="email",
            field=models.EmailField(
                help_text="Укажите вашу электронную почту", max_length=254, unique=True, verbose_name="Email"
            ),
        ),
    ]
