# Generated by Django 5.1.4 on 2025-01-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_newsletter_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="body_letter",
            field=models.TextField(blank=True, null=True, verbose_name="Тело письма"),
        ),
    ]
