# Generated by Django 5.1.4 on 2025-01-30 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_message_create_at_alter_message_body_letter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingrecipient",
            name="email",
            field=models.EmailField(
                help_text="Укажите вашу электронную почту",
                max_length=254,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="Email",
            ),
        ),
    ]
