# Generated by Django 5.1.4 on 2025-01-30 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_mailingrecipient_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("successfully", "Успешно"), ("not_successfully", "Не успешно")],
                        default="not_successfully",
                        max_length=20,
                        verbose_name="Успешность рассылки",
                    ),
                ),
                ("mail_response", models.TextField(blank=True, null=True, verbose_name="Ответ почтового сервера")),
                (
                    "newsletter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mailingattempts",
                        to="mailing.newsletter",
                        verbose_name="Попытка рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылки",
                "ordering": ["status"],
            },
        ),
    ]
