# Generated by Django 5.1.4 on 2025-01-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_mailingattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="last_sending",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время последней рассылки"),
        ),
    ]
