# Generated by Django 5.1.4 on 2025-02-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_alter_newsletter_last_sending"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "ordering": ["name", "first_sending", "last_sending"],
                "permissions": [("can_disable_newsletter", "Can disable newsletter")],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
