# Generated by Django 5.1.4 on 2025-02-04 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_mailingrecipient_owner_message_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingattempt",
            name="email_recipient",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                choices=[("success", "Успешно"), ("failure", "Не успешно")],
                default="success",
                max_length=20,
                verbose_name="Успешность рассылки",
            ),
        ),
    ]
