# Generated by Django 5.1.4 on 2025-02-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0009_mailingattempt_email_recipient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="email_recipient",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email"),
        ),
    ]
